# Test data for login tests
valid_credentials:
  username: "standard_user"
  password: "secret_sauce"
  expected_title: "Products"

invalid_credentials:
  username: "locked_out_user"
  password: "wrong_password"
  expected_error: "Sorry, this user has been locked out."

edge_cases:
  empty_username:
    username: ""
    password: "secret_sauce"
    expected_error: "Username is required"
  empty_password:
    username: "standard_user"
    password: ""
    expected_error: "Password is required"
